version: "3.3"
services:

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - flaskserver

  flaskserver:
    container_name: flaskserver
    build:
      context: ./flaskserver
    networks:
      - default
    volumes:
      - "./flaskserver/data:/data"
      - "./flaskserver/templates:/flaskserver/templates"

  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
    networks:
      - default

  krrruncher:
    restart: always
    build:
       context: ./krrruncher
    networks:
      - default
    depends_on:
      - rabbitmq

  websocketserver:
    container_name: websocketserver
    restart: always
    build:
      context: ./websocketserver
    networks:
      - default
    depends_on:
      - rabbitmq
    volumes:
      # map this file into container from host so that you don't have to do full docker rebuild everytime you
      # edit the file
      - "./websocketserver/websocketserver.py:/websocketserver/websocketserver.py"
    
networks:
  default: {}